export const loginAccountSchema = {
	summary: "Login a user account",
	description:
		"Logs in a user account with email/password or OAuth credentials.",
	tags: ["Users: Accounts"],
	body: {
		type: "object",
		properties: {
			email: {
				type: "string",
				format: "email",
				description: "User email address",
			},
			password: {
				type: "string",
				description: "User password (8-64 chars)",
			},
			username: {
				type: "string",
				description: "Unique username (3-20 chars, letters, numbers, underscores)",
			},
			rememberMe: {
				type: "boolean",
				default: false,
				description: "Whether to remember the user for future sessions",
			},
		},
		allOf: [
			{
				anyOf: [
					{ required: ["email"] },
					{ required: ["username"] },
				],
			},
			{ required: ["password"] },
		],
	},
	response: {
		202: {
			description: "Login accepted (requires 2FA verification).",
			type: "object",
			properties: {
				message: { type: "string" },
			},
		},
		400: {
			description: "Bad request — missing or invalid fields",
			type: "object",
			properties: { message: { type: "string" } },
		},
		429: {
			description: "Too many login attempts",
			type: "object",
			properties: { message: { type: "string" } },
		},
		500: {
			description: "Internal server error",
			type: "object",
			properties: { message: { type: "string" } },
		},
	},
};

export const loginPatchSchema = {
	summary: "Verify 2FA token and upgrade partial session",
	description:
		"Verifies a user's 2FA token. If valid, upgrades the partial session to an active session and extends the session duration.",
	tags: ["Users: Accounts"],
	body: {
		type: "object",
		required: ["token"],
		properties: {
			token: {
				type: "string",
				description: "2FA token generated by the user's authenticator app or 2FA device",
			},
		},
	},
	response: {
		200: {
			description: "2FA verification successful. Session upgraded.",
			type: "object",
			properties: {
				message: { type: "string" },
				user: {
					type: "object",
					properties: {
						id: { type: "string" },
					},
				},
			},
		},
		400: {
			description: "Bad request — missing or invalid fields, or no partial session to upgrade.",
			type: "object",
			properties: { message: { type: "string" } },
		},
		401: {
			description: "Invalid or expired 2FA token.",
			type: "object",
			properties: { message: { type: "string" } },
		},
		429: {
			description: "Too many login attempts",
			type: "object",
			properties: { message: { type: "string" } },
		},
		500: {
			description: "Internal server error during 2FA verification.",
			type: "object",
			properties: { message: { type: "string" } },
		},
	},
};

